### ISSUE TITLE
KNV keeps adding two newlines

### ISSUE THREAD

**Issue by S1SYPHOS** [fundevogel/select-novelties#2]
.. leading to `null` type ISBNs and error:

```
PHP Notice:  Trying to access array offset on value of type bool in /home/two-brain/Documents/projects/fundevogel/recommended-novelties/scripts/vendor/fundevogel/pcbis2pdf/lib/PCBIS2PDF.php on line 577
NULL
PHP Notice:  Trying to access array offset on value of type bool in /home/two-brain/Documents/projects/fundevogel/recommended-novelties/scripts/vendor/fundevogel/pcbis2pdf/lib/PCBIS2PDF.php on line 578
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to PCBIS2PDF\Helpers\Butler::validateISBN() must be of the type string, null given, called in /home/two-brain/Documents/projects/fundevogel/recommended-novelties/scripts/vendor/fundevogel/pcbis2pdf/lib/PCBIS2PDF.php on line 578 and defined in /home/two-brain/Documents/projects/fundevogel/recommended-novelties/scripts/vendor/fundevogel/pcbis2pdf/lib/Helpers/Butler.php:633
Stack trace:
#0 /home/two-brain/Documents/projects/fundevogel/recommended-novelties/scripts/vendor/fundevogel/pcbis2pdf/lib/PCBIS2PDF.php(578): PCBIS2PDF\Helpers\Butler::validateISBN()
#1 /home/two-brain/Documents/projects/fundevogel/recommended-novelties/scripts/fetch_api.php(17): PCBIS2PDF\PCBIS2PDF->processData()
#2 {main}
  thrown in /home/two-brain/Documents/projects/fundevogel/recommended-novelties/scripts/vendor/fundevogel/pcbis2pdf/lib/Helpers/Butler.php on line 633
```

**Comment by S1SYPHOS** [comment]
This was fixed when introducing `new_issue.bash` helper script, see [here](https://github.com/fundevogel/scribus-toolbox/commits/master/new_issue.bash).
